# Generated by Django 6.0 on 2026-02-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('activation', 'Activation'), ('login', 'Login'), ('reset', 'Reset')], default='activation', max_length=20),
        ),
    ]
