version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: beehive-backend
    restart: unless-stopped
    volumes:
      - ./Backend/data:/app/data
      - ./Backend/staticfiles:/app/staticfiles
      - ./Backend/local.conf:/app/local.conf:ro
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://kubol.ir
    container_name: beehive-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
