# Generated by Django 6.0 on 2026-01-05 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('categories', models.JSONField(default=list)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('spam', 'Spam'), ('duplicate', 'Duplicate'), ('fake', 'Fake'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='items.item')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Report',
                'verbose_name_plural': 'Item Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-created_at'], name='items_item_created_3eaa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='items_item_status_819478_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active'], name='items_item_is_acti_391f0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemreport',
            unique_together={('item', 'reporter')},
        ),
    ]
